### ISSUE TITLE
failed to start broker failed to create mounts: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by kumarganesh2814** [hashicorp/vault-service-broker#45] opened 2019-03-20 10:40 UTC
Hi Team,

While Deploying cloud-foundry-vault-service-broker as below
https://www.hashicorp.com/blog/cloud-foundry-vault-service-broker

Whenever we do cf start vault-broker

I have tried putting but no use. Please guide

```cf set-env vault-broker VAULT_ADDR "https://10.119.69.204:8200"
cf set-env vault-broker VAULT_TOKEN "*************"
cf set-env vault-broker SECURITY_USER_NAME "vadmin"
cf set-env vault-broker SECURITY_USER_PASSWORD "*********"
cf set-env vault-broker TRUST_CERTS "10.119.69.204:8200"
cf set-env vault-broker VAULT_SKIP_VERIFY "true"

**Comment by kumarganesh2814** [comment] 2019-03-20 10:41
Errors:
```2019-03-20T03:30:53.84-0700 [CELL/0]     OUT Starting health monitoring of container
2019-03-20T03:30:53.95-0700 [APP/PROC/WEB/0]OUT [INFO] starting broker
2019-03-20T03:30:53.95-0700 [APP/PROC/WEB/0]OUT [DEBUG] creating mounts cf/broker=generic
2019-03-20T03:30:57.92-0700 [APP/PROC/WEB/0]OUT [ERR] failed to start broker: failed to create mounts: Get https://10.119.69.204:8200/v1/sys/mounts: x509: certificate signed by unknown authority
2019-03-20T03:30:57.94-0700 [APP/PROC/WEB/0]OUT Exit status 1
2019-03-20T03:30:57.94-0700 [CELL/SSHD/0]OUT Exit status 0
2019-03-20T03:30:57.97-0700 [API/0]      OUT Process has crashed with type: "web"
2019-03-20T03:30:57.97-0700 [CELL/0]     OUT Stopping instance 2ba34cf6-548a-41ed-4040-ffc9
2019-03-20T03:30:57.97-0700 [CELL/0]     OUT Destroying container
2019-03-20T03:30:57.97-0700 [API/0]      OUT App instance exited with guid 249fd857-2b41-43a2-aa5e-581c0dc5e9e3 payload: {"instance"=>"2ba34cf6-548a-41ed-4040-ffc9", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>1, "crash_timestamp"=>1553077857955191766, "version"=>"558c6c3b-9948-4fa5-819f-b80ab8a86355"}

**Comment by tyrannosaurus-becks** [comment] 2019-03-21 16:28
Hi @kumarganesh2814 , thanks for opening this issue!

In looking at the variables you're setting above, I notice that some of them like `VAULT_SKIP_VERIFY` aren't currently supported in the service broker, nor are they mentioned in the README. The most recent instructions are probably in the README.

**Comment by tyrannosaurus-becks** [comment] 2019-03-25 16:48
Closing this issue as the cause seems to be identified. If you're interested in requesting support for additional configuration, feel free to open a separate issue explaining your request and use case. Thank you!

**Closed by tyrannosaurus-becks** 2019-03-25 16:48 UTC

**Comment by kumarganesh2814** [comment] 2019-03-26 18:47
@tyrannosaurus-becks Hi,
I tried removing cf set-env vault-broker VAULT_SKIP_VERIFY "true" but issue is still same. Please advise.

Best Regards
Ganesh Kumar
